version: "3.4"

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_DOMAIN=https://dev1.cf:3200
      - NEXT_PUBLIC_VERSION=dev
      - NEXT_PUBLIC_IMG_PREFIX=f8c06ef0-5fb6-48b4-a9d1-15b765453033
      - SERVER_BASE=http://server:3001
    volumes:
      - ./app:/app
      - /app/node_modules/

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    environment:
      - APP_DOMAIN=https://dev1.cf:3200
      - NODE_ENV=development
      - SECRET=secret
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DATABASE=dev
      - S3_Endpoint=http://minio:9000
      - S3_Region=ru-central1
      - S3_Bucket=f8c06ef0-5fb6-48b4-a9d1-15b765453033
      - S3_AccessKey=SYmuS-lZ3J39PjejLCiZ
      - S3_SecretKey=5yGXYIjUTw5aecYgGoBudpMs0drw26csJY39dVkR
      - TZ=Europe/Moscow
    volumes:
      - ./server:/app
      - /app/node_modules/
    depends_on:
      - db
      - minio

  db:
    image: postgres:12.4-alpine
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    logging:
      driver: none

  minio:
    image: minio/minio:RELEASE.2020-10-18T21-54-12Z
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./.data/minio:/data
    environment:
      MINIO_ACCESS_KEY: SYmuS-lZ3J39PjejLCiZ
      MINIO_SECRET_KEY: 5yGXYIjUTw5aecYgGoBudpMs0drw26csJY39dVkR

  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - app
      - server
    ports:
      - 3200:3030
    volumes:
      - ./nginx/dev/conf:/etc/nginx/conf
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf